from _schematic_helpers import *
fig=plt.figure(figsize=(13.2,4.9))
gs=fig.add_gridspec(1,3,width_ratios=[1.0,0.6,1.0],wspace=0.12)
# A builder
a=fig.add_subplot(gs[0,0]); a.set_xlim(0,10); a.set_ylim(0,10); a.axis("off")
I=node(a,(2.3,8.4),"I",C_IN); P=node(a,(7.7,8.4),"P",C_IN)
Li=node(a,(2.3,4.4),"L$_i$",C_LAT); Lp=node(a,(7.7,4.4),"L$_p$",C_LAT)
H=node(a,(5.0,6.4),"INH",C_DEP,r=0.5)
exc(a,I,H,color=C_IN); exc(a,P,H,color=C_IN)
exc(a,H,Li,color=C_DEP); exc(a,H,Lp,color=C_DEP)
exc(a,I,Li,color=C_EXC,ls=(0,(2.5,2.5))); exc(a,P,Lp,color=C_EXC,ls=(0,(2.5,2.5)))
a.text(5,9.5,"A  Builder",ha="center",fontsize=11,weight="bold")
a.text(3.7,6.4,"+",ha="center",va="center",color=C_DEP,fontsize=17,weight="bold")
a.text(6.3,6.4,"+",ha="center",va="center",color=C_DEP,fontsize=17,weight="bold")
a.text(5,2.3,"Depolarising GABA (+): the hub co-activates\nthe laterals; GDP-like bursts grow the\nexcitatory arms (dashed).",ha="center",fontsize=8.1,color="#333")
# B switch
b=fig.add_subplot(gs[0,1]); b.set_xlim(0,10); b.set_ylim(0,10); b.axis("off")
b.text(5,9.5,"B  The switch",ha="center",fontsize=11,weight="bold")
b.plot([5,5],[2.6,7.6],color="#ccc",lw=9,solid_capstyle="round",zorder=1)
b.plot([3.9,6.1],[5.0,5.0],color="#777",lw=1,ls=":"); b.text(6.25,5.0,"V$_{thr}$",fontsize=8,color="#777",va="center")
b.add_patch(Circle((5,6.9),0.30,fc=C_DEP,ec="k",zorder=3)); b.text(2.7,6.9,"E$_{Cl}$ high\ndepol (+)",fontsize=8,color=C_DEP,va="center",ha="center")
b.add_patch(Circle((5,3.1),0.30,fc=C_INH,ec="k",zorder=3)); b.text(2.7,3.1,"E$_{Cl}$ low\nshunt (\u2212)",fontsize=8,color=C_INH,va="center",ha="center")
b.annotate("",xy=(5,3.9),xytext=(5,6.1),arrowprops=dict(arrowstyle="-|>",color=C_EXC,lw=2.6,mutation_scale=18),zorder=4)
b.text(7.0,5.0,"KCC2 \u2191\n[Cl$^-$] \u2193",fontsize=8.6,color=C_EXC,va="center",weight="bold")
b.text(5,1.4,"$E_{Cl}$ falls; GABA\nflips  +  \u2192  \u2212 .",ha="center",fontsize=8.1,color="#333")
# C governor (simplified: hub now shunts laterals -> read-out; no F+/F-, no equations)
c=fig.add_subplot(gs[0,2]); c.set_xlim(0,10); c.set_ylim(0,10); c.axis("off")
c.text(5,9.5,"C  Governor",ha="center",fontsize=11,weight="bold")
I2=node(c,(2.3,8.4),"I",C_IN); P2=node(c,(7.7,8.4),"P",C_IN)
Li2=node(c,(2.3,5.0),"L$_i$",C_LAT); Lp2=node(c,(7.7,5.0),"L$_p$",C_LAT)
H2=node(c,(5.0,6.6),"INH",C_INH,r=0.5)
R=node(c,(5.0,2.4),"read-out",C_OUT,r=0.62,fs=8.5)
exc(c,I2,Li2,color=C_EXC); exc(c,P2,Lp2,color=C_EXC)
exc(c,I2,H2,color=C_IN); exc(c,P2,H2,color=C_IN)
inh(c,H2,Li2,divide=True); inh(c,H2,Lp2,divide=True)
exc(c,Li2,R,color=C_EXC,rb=0.62); exc(c,Lp2,R,color=C_EXC,rb=0.62)
c.text(3.55,6.6,"\u2212",ha="center",va="center",color=C_INH,fontsize=17,weight="bold")
c.text(6.45,6.6,"\u2212",ha="center",va="center",color=C_INH,fontsize=17,weight="bold")
c.text(5,0.9,"Shunting GABA (\u2212): the same hub now\ndivides the laterals \u2014 a gain-controlling\ngovernor (detailed in Fig. 2).",ha="center",fontsize=8.1,color="#333")
h=[ml.Line2D([],[],color=C_EXC,lw=2.4,marker=">",ms=7,label="excitatory"),
   ml.Line2D([],[],color=C_INH,lw=2.4,marker="o",ms=7,label="inhibitory / shunt (\u00f7)"),
   ml.Line2D([],[],color=C_EXC,lw=2.0,ls=(0,(2.5,2.5)),label="arm being grown")]
fig.legend(handles=h,loc="lower center",ncol=3,frameon=False,fontsize=8.6,bbox_to_anchor=(0.5,-0.04))
fig.suptitle("The developmental sequence: one inhibitory hub, three roles \u2014 builder $\\to$ switch $\\to$ governor",fontsize=12,weight="bold",y=1.02)
fig.savefig("motif_dev_en.png",dpi=170,bbox_inches="tight",facecolor="white")
from PIL import Image; print("motif_dev",Image.open("motif_dev_en.png").size)
